[project]
name = "modulo-agendamento"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "langchain-core>=0.3.63",
    "langchain-openai==0.3.16",
    "langgraph>=0.4.7",
    "pydantic-settings>=2.9.1",
]
